name: cd cd on github

on:
  push:
    branches: [ "release" ]
  pull_request:
    branches: [ "release" ]

jobs:
  Build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.12.2]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Update caniuse-lite
      run: npx update-browserslist-db@latest

    - name: Install dependencies
      run: npm install

    - name: Install missing Babel plugin
      run: npm install --save-dev @babel/plugin-proposal-private-property-in-object

    - name: Build test
      run: npm run build

    - name: Test
      run: npm run test

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_EMAIL }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build Docker image
      run: docker build -t lffdevops/react-app:latest .

    - name: Show Images
      run: docker images

    - name: Push Docker image to Docker Hub
      run: docker push lffdevops/react-app:latest
